# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b7c85380a92d11be5ad623501c4ce3326441e939fc24c1121a2b9b4a688bbe86b3885fef817b6d7053299ef774c427e3176a66e86f8470c81fec66c072844e

test:
  secret_key_base: e4adb245aa5dabdb55d2cf3e5ef241aa910de419f924bcf90426b7f581f9715e6bd5edfb1d1abef3f82096315312a171d6a85d3dce8a2df51d96cc690a599be1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
